[build]
cmd = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
MONGO_URL = "${{MONGO_URL}}"
DB_NAME = "shelfchef_production"
PORT = "8000"