name: Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        pip install -r requirements.txt
    
    - name: Run Black
      working-directory: ./backend
      run: black --check .
    
    - name: Run isort
      working-directory: ./backend
      run: isort --check-only .
    
    - name: Run flake8
      working-directory: ./backend
      run: flake8 .
    
    - name: Run mypy
      working-directory: ./backend
      run: mypy . --ignore-missing-imports

  lint-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
    
    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
    
    - name: Run ESLint
      working-directory: ./frontend
      run: yarn lint
    
    - name: Run Prettier
      working-directory: ./frontend
      run: yarn prettier --check src/